apiVersion: apps/v1
kind: Deployment
metadata:
  name: hascheduller
  namespace: pml
  labels:
    app: hascheduller
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: hascheduller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hascheduller
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name:hascheduller
          image: "{{ .Values.image.hascheduller.repository }}:{{ .Values.image.hascheduller.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
