apiVersion: apps/v1
kind: Deployment
metadata:
  name: controllermanager
  namespace: {{ .Release.Namespace }}
  labels:
    app: controllermanager
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: controllermanager
  template:
    metadata:
      labels:
        app.kubernetes.io/name: controllermanager
    spec:
      containers:
        - command:
            - /manager
          args:
            - --enable-leader-election
          image: "{{ .Values.image.controllermanager.repository }}:{{ .Values.image.controllermanager.tag }}"
          name: controllermanager
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 30Mi
            requests:
              cpu: 100m
              memory: 20Mi
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
