apiVersion: apps/v1
kind: Deployment
metadata:
  name: controllermanager
  namespace: pml
  labels:
    app: controllermanager
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: controllermanager
  template:
    metadata:
      labels:
        app.kubernetes.io/name: controllermanager
    spec:
    containers:
      - name:controllermanager
        image: "{{ .Values.image.controllermanager.repository }}:{{ .Values.image.controllermanager.tag }}"
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 8080
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
    {{- with .Values.nodeSelector }}
    nodeSelector:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
    affinity:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
    tolerations:
      {{- toYaml . | nindent 8 }}
    {{- end }}
